# Generated by Django 4.2.1 on 2023-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('subtitle1', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe1', models.TextField(blank=True, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe2', models.TextField(blank=True, null=True)),
                ('subtitle3', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe3', models.TextField(blank=True, null=True)),
                ('subtitle4', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe4', models.TextField(blank=True, null=True)),
                ('subtitle5', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe5', models.TextField(blank=True, null=True)),
                ('subtitle6', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphe6', models.TextField(blank=True, null=True)),
                ('coonclusion', models.TextField()),
            ],
        ),
    ]
