# Generated by Django 4.2.1 on 2023-07-16 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=datetime.datetime(2023, 7, 16, 19, 21, 47, 619816, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
